// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE

import * as Block from "bs-platform/lib/es6/block.js";
import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as ReasonReact from "reason-react/src/ReasonReact.js";

var component = ReasonReact.statelessComponent("Form");

var card = {
  border: "2px solid #898989",
  clear: "right",
  float: "right",
  padding: "1rem",
  borderRadius: "4px"
};

var Styles = /* module */[/* card */card];

function make(ctx, appSend, _children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (_self) {
              return React.createElement("form", {
                          onSubmit: (function (ev) {
                              ev.preventDefault();
                              Curry._1(appSend, /* UpdateInput */Block.__(0, [
                                      ctx[/* input */0],
                                      ctx[/* utilisateur */1]
                                    ]));
                              return Curry._1(appSend, /* Search */1);
                            })
                        }, React.createElement("label", {
                              htmlFor: "search"
                            }, "Search"), React.createElement("button", {
                              type: "submit"
                            }, "Submit Search"));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

export {
  component ,
  Styles ,
  make ,
  
}
/* component Not a pure module */
