// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReasonReact from "reason-react/src/ReasonReact.js";
import * as Form$Gitsearch from "./components/Form.bs.js";
import * as Root$Gitsearch from "./Root.bs.js";
import * as Results$Gitsearch from "./components/Results.bs.js";
import * as SendMessage$Gitsearch from "./components/SendMessage.bs.js";

var component = ReasonReact.reducerComponent("App");

var divprinc = {
  border: "2px solid #898989",
  clear: "right",
  float: "right",
  height: "1000px",
  overflow: "auto",
  padding: "1rem",
  width: "500px",
  borderRadius: "4px"
};

function make(_children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (param) {
              var send = param[/* send */3];
              var state = param[/* state */1];
              return React.createElement("div", {
                          style: divprinc
                        }, ReasonReact.element(undefined, undefined, Form$Gitsearch.make(/* record */[
                                  /* input */"in",
                                  /* utilisateur */"1"
                                ], send, /* array */[])), ReasonReact.element(undefined, undefined, SendMessage$Gitsearch.make(/* record */[
                                  /* input */"in",
                                  /* utilisateur */"1",
                                  /* text */state[/* text */2]
                                ], send, /* array */[])), ReasonReact.element(undefined, undefined, Results$Gitsearch.make(/* record */[
                                  /* isLoading */state[/* isLoading */3],
                                  /* results */state[/* results */4]
                                ], "1", send, /* array */[])));
            }),
          /* initialState */(function (param) {
              return Root$Gitsearch.initialAppState;
            }),
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */Root$Gitsearch.reducer,
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

export {
  component ,
  divprinc ,
  make ,
  
}
/* component Not a pure module */
