// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE

import * as ReactDOMRe from "reason-react/src/ReactDOMRe.js";
import * as ReasonReact from "reason-react/src/ReasonReact.js";
import * as App$Gitsearch from "./App.bs.js";

((require('bulma/bulma.sass')));

ReactDOMRe.renderToElementWithId(ReasonReact.element(undefined, undefined, App$Gitsearch.make(/* array */[])), "app");

export {
  
}

/*  Not a pure module */
